const stockMarketTypes = {
    ERROR: "ERROR",
    DIVIDEND_FORM_ERROR: "DIVIDEND_FORM_ERROR",
    PERATIO_FORM_ERROR: "PERATIO_FORM_ERROR",
    RETRIEVE_STOCK: "RETRIEVE_STOCK",
    RETRIEVE_TRADE: "RETRIEVE_TRADE"
};

export default stockMarketTypes;